# -*- coding: utf-8 -*-
"""Final.ipynb

Automatically generated by Colaboratory.

Original file is located at
"""

import pandas as pd

df = pd.read_csv("staticfiles/Final_file.csv")
df.drop(['0'],axis=1)
df['Condition'] = df['Condition'].str.lower()

def solve(query):

  query=query.lower()
  df_temp = df[df['Condition']==query]
  df_temp = df_temp.drop(['0','Condition'],axis=1)
  df_final = df_temp.sort_values(by=['Value'],ascending=False)
  ans = df_final['Drugname'].tolist()
  return ans
'''

condition_name = input()
output = solve(condition_name,df)
output
'''