# Generated by Django 3.1.4 on 2021-02-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.AutoField(primary_key=True, serialize=False)),
                ('hospital', models.CharField(max_length=20, null=True)),
                ('phno', models.CharField(max_length=15)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
