# Generated by Django 3.1.4 on 2021-02-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.AddField(
            model_name='doctor',
            name='id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='lno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='sp',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phno',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
