# Generated by Django 3.1.4 on 2021-02-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mg', '0002_auto_20210227_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
