# Generated by Django 3.1.4 on 2021-02-27 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('mg', '0004_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='usr',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount'),
            preserve_default=False,
        ),
    ]
