# Generated by Django 3.1.4 on 2021-02-27 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mg', '0006_auto_20210227_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='usr',
        ),
    ]
