# Generated by Django 3.1.4 on 2021-02-27 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('mg', '0009_doctor_usr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='usr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='socialaccount.socialaccount'),
        ),
    ]
