# Generated by Django 3.1.4 on 2021-02-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mg', '0011_auto_20210227_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='forum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField(null=True)),
            ],
        ),
    ]
